# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6899c6c2aabeae27a383a5c7f185b8b78b8b13969a8d3a1b28c31f2d49078f1973ba27a3592357e69d24035a926f65d99b2882dfe6e6f48e4bb8ed27c2a2a69

test:
  secret_key_base: 060fdd42ea9f67f3a1935bb2120360f7ccf6ffde7d4774d167cf4c69baa4dbe463566b647274df6f22b6a75f9b9cf91f90ae07bc619aae37e8478ef4f2c155da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
